# Generated by Django 5.1.1 on 2024-10-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5plus', '5+ Years')], max_length=20)),
                ('recent_company', models.CharField(blank=True, max_length=100, null=True)),
                ('recent_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_marks', models.CharField(max_length=10)),
                ('school_passing_year', models.CharField(max_length=4)),
                ('college_name', models.CharField(max_length=100)),
                ('college_marks', models.CharField(max_length=10)),
                ('college_passing_year', models.CharField(max_length=4)),
                ('skills', models.JSONField()),
                ('certifications', models.JSONField()),
                ('languages', models.JSONField()),
                ('hobbies', models.JSONField()),
            ],
        ),
    ]
