# Generated by Django 5.1.2 on 2024-11-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='email',
        ),
    ]
